"""remove url images

Revision ID: 4e47dcecf9b7
Revises: 449e7be87951
Create Date: 2019-03-10 15:46:42.861823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e47dcecf9b7'
down_revision = '449e7be87951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_model', 'photo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_model', sa.Column('photo_url', sa.VARCHAR(length=254), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
