"""empty message

Revision ID: 834a30207096
Revises: 
Create Date: 2019-03-10 13:29:33.798396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834a30207096'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_filename', sa.String(length=80), nullable=False),
    sa.Column('photo_url', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_filename'),
    sa.UniqueConstraint('photo_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_model')
    # ### end Alembic commands ###
