"""add url photo

Revision ID: 9653b39ee386
Revises: e8f7e6ff0b52
Create Date: 2019-03-10 14:45:21.244442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9653b39ee386'
down_revision = 'e8f7e6ff0b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_model', sa.Column('photo_url', sa.String(length=254), nullable=False))
    op.create_unique_constraint(None, 'photo_model', ['photo_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo_model', type_='unique')
    op.drop_column('photo_model', 'photo_url')
    # ### end Alembic commands ###
