"""Add File Upload

Revision ID: b8b3e3b85ed0
Revises: d18f75c81900
Create Date: 2019-03-18 14:47:08.563790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b3e3b85ed0'
down_revision = 'd18f75c81900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_model', sa.Column('doc', sa.LargeBinary(), nullable=True))
    op.add_column('photo_model', sa.Column('doc_filename', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_model', 'doc_filename')
    op.drop_column('photo_model', 'doc')
    # ### end Alembic commands ###
