"""Add name field

Revision ID: d18f75c81900
Revises: 4e47dcecf9b7
Create Date: 2019-03-10 15:53:34.017580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18f75c81900'
down_revision = '4e47dcecf9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_model', sa.Column('name', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_model', 'name')
    # ### end Alembic commands ###
