"""add photo column binary

Revision ID: ded2138754f0
Revises: b8b3e3b85ed0
Create Date: 2019-04-02 00:20:52.394649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded2138754f0'
down_revision = 'b8b3e3b85ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_model', sa.Column('photo', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_model', 'photo')
    # ### end Alembic commands ###
